- hosts: playground
  become: yes
  tasks:
    - name: system update
      yum:
        name: '*'
        state: latest

    - name: install repos
      yum:
        name:
          - epel-release
          - https://rpms.remirepo.net/enterprise/remi-release-7.rpm
        state: present

    - name: disable repos
      replace:
        path: /etc/yum.repos.d/{{item}}
        regexp: 'enabled *= *1'
        replace: 'enabled=0'
      loop:
        - epel.repo
        - remi.repo
        - remi-php70.repo

    # - name: remove packages
    #   yum:
    #     name:
    #       - httpd
    #       - php
    #       - mariadb
    #     state: absent

    - name: install packages
      yum:
        name:
          - httpd-devel
          - php
          - php-devel
          - php-mbstring
          - php-mysqlnd
          - php-pdo
          - mariadb-server
        enablerepo: "epel,remi-php70"
